### ISSUE TITLE
Wrong version number in release notes of v202202.0.0

### ISSUE THREAD

**Issue by ajaust** [precice/vm#32]
The first sentence in the release notes states

```text
This is a scheduled release in the context of the preCICE distribution 2002.0.
```

I assume this should be `2202.0`, i.e.

```text
This is a scheduled release in the context of the preCICE distribution 2202.0.
```
such that it is consistent with your versioning scheme `(yymm).(distribution revision)`.

Note that these erroneous release notes are also on VagrantCloud: <https://app.vagrantup.com/precice/boxes/precice-vm/versions/202202.0.0>

**Comment by MakisH** [comment]
Thanks a lot for the very quick reaction! I have been dreading all these different version numbers (and especially the "2021" muscle memory). Hopefully, this was only a typo in the description.
