### ISSUE TITLE
FEniCS is not working

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/vm#4]
I tried running `tutorials/HT/partitioned-heat/fenics-fenics` and got an error:

```
$ python3 heat.py
...
ModuleNotFoundError: No module named 'fenics'
```

**Comment by MakisH** [comment]
FEniCS is installed in the develop branch. Please try again and close. :)

**Comment by BenjaminRodenberg** [comment]
I checked the current version from develop and now we get the following error:

```
vagrant@precicevm:~/Desktop$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fenics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/usr/lib/petsc/lib/python3/dist-packages/dolfin/__init__.py", line 144, in <module>
    from .fem.assembling import (assemble, assemble_system, assemble_multimesh, assemble_mixed,
  File "/usr/lib/petsc/lib/python3/dist-packages/dolfin/fem/assembling.py", line 38, in <module>
    from ufl.form import sub_forms_by_domain
ImportError: cannot import name 'sub_forms_by_domain' from 'ufl.form' (/home/vagrant/.local/lib/python3.8/site-packages/ufl/form.py)
>>> 
```

This is a good old friend of mine: See https://github.com/precice/fenics-adapter/issues/103 and especially https://fenicsproject.discourse.group/t/installing-python-package-with-fenics-dependency-breaks-fenics-installation/4476. I would suggest implementing the fix from the forum post directly in the vm.

I already tried this manually in the vm and it seems to work:
```
vagrant@precicevm:~/Desktop$ pip3 uninstall -y fenics-ufl
Found existing installation: fenics-ufl 2019.1.0
Uninstalling fenics-ufl-2019.1.0:
  Successfully uninstalled fenics-ufl-2019.1.0
vagrant@precicevm:~/Desktop$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fenics
>>> 
```
Let's keep this issue open. Problem has slightly shifted, but is still there.

**Comment by MakisH** [comment]
I am already doing this, so I am confused:
https://github.com/precice/vm/blob/7d1f1fb6c92eaadad002dfccf4b43c8c155afb82/provisioning/install-fenics.sh#L15

**Comment by BenjaminRodenberg** [comment]
> I am already doing this, so I am confused:
> 
> https://github.com/precice/vm/blob/7d1f1fb6c92eaadad002dfccf4b43c8c155afb82/provisioning/install-fenics.sh#L15

Hmm... this also brings for me a new layer of confusion into https://github.com/precice/fenics-adapter/issues/103.

**Comment by vidanovic** [comment]
The same problem here:

    from fenics import *
ModuleNotFoundError: No module named 'fenics'

**Comment by BenjaminRodenberg** [comment]
> The same problem here:
> 
> ```
> from fenics import *
> ```
> 
> ModuleNotFoundError: No module named 'fenics'

@vidanovic As far as I understand the [history](https://github.com/precice/vm/commits/main) of our current release (https://github.com/precice/vm/releases/tag/v202211.0.0), the fix from #64 is not included yet. Can you try to uninstall `fenics-ufl` as described above? (I'm assuming you are using v202211.0.0)

**Comment by vidanovic** [comment]
@BenjaminRodenberg Yes, I have tried to uninstall `fenics-ufl` and it did not help. Will try later when this is fixed.
Best!

**Comment by MakisH** [comment]
@vidanovic we are not planning any release of the vm (even a bugfix) till the next preCICE Distribution (which will come after preCICE v3 is released, not before summer). Do you need this fix released soon?

**Comment by vidanovic** [comment]
@MakisH No, it is not urgent at all. It was more of a test against some of the equations I am developing in my FEM engine.
