### ISSUE TITLE
Add FEniCSx to the vm

### ISSUE THREAD

**Issue by IshaanDesai** [precice/vm#65]
FEniCSx was recently added as a participant to the partitioned-heat-conduction tutorial case: https://github.com/precice/tutorials/pull/317. FEniCSx needs to be added to the vm for the tutorial case to work.

**Comment by MakisH** [comment]
Note that we still want to keep the legacy FEniCS for some time.

**Comment by MakisH** [comment]
The FEniCSx tutorials have been removed from the current state of the tutorials.

I am closing this for now, please reopen once it becomes relevant again.
