### ISSUE TITLE
Update VTK version

### ISSUE THREAD

**Issue by MakisH** [precice/vm#66]
https://github.com/precice/vm/blob/a37b13a50ade7658e63bd17bbe3230df085bba7f/provisioning/install-aste.sh#LL5C36-L5C36

for ASTE, try VTK 9 from PIP

Related to https://github.com/precice/aste/issues/171

**Comment by davidscn** [comment]
IIRC, this was the reason I upgraded the version in the CI as well https://github.com/precice/aste/commit/9ecaddd7924ce2fe82032bc672d0f23fa89f8bc6

I'm not sure if pip-only installations are sufficient. In aste, we also use the C++ interface and I always used to compile my own version of VTK. Instructions are provided in the [VTK docs](https://docs.vtk.org/en/latest/build_instructions/index.html). TL;DR; you can [download a version](https://vtk.org/download/) and use CMake to build it.

**Comment by MakisH** [comment]
Then I will try with VTK 9 from APT, and then we need to check again once we want to upgrade to Ubuntu 22.04 (or 24.04), see #45.

**Comment by MakisH** [comment]
VTK 7 is fine with the current state of the VM (Ubuntu 20.04, NumPy from APT) and the latest ASTE. The VM builds and the `aste-turbine` tutorial runs.

We will anyway need to upgrade VTK once we upgrade the Ubuntu version. Closing for now.
