### ISSUE TITLE
Nutils for offline use

### ISSUE THREAD

**Issue by MakisH** [precice/vm#85]
In https://github.com/precice/vm/pull/71, I removed Nutils as tutorials now install it on first run.
However, we still sometimes need to run Nutils in offline environments (e.g., a course during a conference, in a remote room, with strange Wi-Fi access, if at all).

Maybe having a default Nutils installation isn't a bad idea after all.

**Comment by uekerman** [comment]
Are there really cases, where we have no internet? We then probably have more problems :D
Isn't there a way to cache things from PyPI without installing?
Having user-wide installations of Python packages will anyway be discouraged eventually, so what we have right now sounds more sustainable to me.

**Comment by MakisH** [comment]
The main case I think is that externals come to a conference in Stuttgart. Is there guest wlwn there?

**Comment by MakisH** [comment]
Let's ignore this for now and reopen if we see an actual issue in the wild.
